const FETCHING_AUTH_USER = 'states/auth/FETCHING_AUTH_USER';
const FETCH_AUTH_USER_SUCCESS = 'states/auth/FETCH_AUTH_USER_SUCCESS';
const FETCH_AUTH_USER_FAIL = 'states/auth/FETCH_AUTH_USER_FAIL';
const STORE_AUTH_USER_DATA = 'states/auth/STORE_AUTH_USER_DATA';

export default {
    FETCHING_AUTH_USER,
    FETCH_AUTH_USER_SUCCESS,
    FETCH_AUTH_USER_FAIL,
    STORE_AUTH_USER_DATA
}
